### ISSUE TITLE
[긴급] 이것 때문에 아이폰 유저 떠나가...

### ISSUE THREAD

**Issue by min050410** [BSSM-BSM/BSM-Frontend-V2#7]
## 빅 이슈
<img src="https://user-images.githubusercontent.com/45661217/223984103-899c4356-00f8-4515-adfa-28443e43a857.png" width="40%"></img>
자유게시판이 안눌려집니다!

## 빅 이슈 2
<img src="https://user-images.githubusercontent.com/45661217/223984192-b6e8ce90-9dfc-422b-8fa6-1ba4be5b7373.png" width="40%"></img>

메뉴에서 코드 공유를 눌렀더니
<img src="https://user-images.githubusercontent.com/45661217/223984229-2ffc3971-d2ac-4dcd-ba49-800cda1cedbb.png" width="40%"></img>

공지사항 페이지로 리다이렉트 됩니다.

**Comment by leehj050211** [comment]
[fb67680](https://github.com/BSSM-BSM/BSM-Frontend-V2/commit/fb67680aa53c55a2ac4c4a1d0553327e36439e6e) 커밋에서 해당 이슈를 최종 수정 하였습니다.

**Comment by min050410** [comment]
캬 깔끔하네요. 감사합니다
